### ISSUE TITLE
Support sections

### ISSUE THREAD

**Issue by muuvmuuv** [Xanders/make-help#1]
Cool idea! We use it in all our Makefiles and its way better than all this `fgrep`/`sed` stuff!

Our Makefiles continue to grow more and more so I would like to propose a new feature for sections.

```Makefile
##
## Docker
##

# Start server
start:
	docker-compose up -d --remove-orphans
```

Which would print something like:

```
Usage: make <command> [ARGUMENT1=value1] [ARGUMENT2=value2]

Commands:

 help                                           # Print help

 **DOCKER** (bold and pink?)

 start                                          # Start server
```

**Comment by Xanders** [comment]
Hi! Thanks, I'm glad you found this solution useful! :)

Nice idea, I like it. This week I'll think about how to implement it.

**Comment by muuvmuuv** [comment]
I will also have a look because I never heard about Crystal, and it seems interesting.

**Comment by Xanders** [comment]
Yay, PRs are welcome! :) Crystal is simple yet powerful language. Best in write/run speed ratio, I think. And just as beautiful as Ruby. :)

**Comment by Xanders** [comment]
Done in https://github.com/Xanders/make-help/commit/7aa58f5a4c54561c094b57315300300b69e91782! You can download new version with `docker pull xanders/make-help`. Feel free to reopen the issue if something won't work as expected. Thank you for idea! :)
