### ISSUE TITLE
Makefile parser behaves a bit quirky (or not?)

### ISSUE THREAD

**Issue by Drachenfels** [Xanders/make-help#4]
Hi there,

I decided to try to run your help parser on our existing object, it works more or less as promised but I detected some quirky behaviour that I suspect might be a bug:

My Makefile looks as follows:

```
# specify branch if you want to hardcode deployment to specific location
target ?=
TEST ?= tests/

SOME_VAR := yolo

# Show this help message
# Multiple lines are supported too
# When it's first, both commands works:
# `make`
# `make help`
help:
	@cat $(MAKEFILE_LIST) | docker run --rm -i xanders/make-help

# Build Docker image
build:
	docker build -t xanders/make-help .

# Run `build` and `help` successively
test: build help

##
## Section for authorized contributors
##

# Push image to `https://hub.docker.com`
push:
	docker push xanders/make-help
```

Then running make help gives this output:

![selection-20210414122348](https://user-images.githubusercontent.com/135730/114702725-5673b200-9d1c-11eb-8fcc-74171a4986ff.png)

To fix it, I moved `SOME_VAR := yolo` above first comment:

```
SOME_VAR := yolo

# specify branch if you want to hardcode deployment to specific location
target ?=
TEST ?= tests/

# Show this help message
# Multiple lines are supported too
# When it's first, both commands works:
# `make`
# `make help`
help:
	@cat $(MAKEFILE_LIST) | docker run --rm -i xanders/make-help

# Build Docker image
build:
	docker build -t xanders/make-help .

# Run `build` and `help` successively
test: build help

##
## Section for authorized contributors
##

# Push image to `https://hub.docker.com`
push:
	docker push xanders/make-help
```

And now it behaves as expected:

![selection-20210414122613](https://user-images.githubusercontent.com/135730/114702967-9fc40180-9d1c-11eb-8868-b8970a671230.png)

By pure accident I found a workaround (but I have no clue why it works this way) by adding empty comment lines between `SOME_VAR := yolo` and rest of the code:

```
# specify branch if you want to hardcode deployment to specific location
target ?=
TEST ?= tests/

#

SOME_VAR := yolo

#

# Show this help message
# Multiple lines are supported too
# When it's first, both commands works:
# `make`
# `make help`
help:
	@cat $(MAKEFILE_LIST) | docker run --rm -i xanders/make-help

# Build Docker image
build:
	docker build -t xanders/make-help .

# Run `build` and `help` successively
test: build help

##
## Section for authorized contributors
##

# Push image to `https://hub.docker.com`
push:
	docker push xanders/make-help
```

Again will work as expected.

That makes me thinking, maybe special delimiter in a form `# ---` will mark that from now on it's commands only?

Example:
```
# specify branch if you want to hardcode deployment to specific location
target ?=
TEST ?= tests/

SOME_VAR := yolo

# ---

# Show this help message
# Multiple lines are supported too
# When it's first, both commands works:
# `make`
# `make help`
help:
	@cat $(MAKEFILE_LIST) | docker run --rm -i xanders/make-help

# Build Docker image
build:
	docker build -t xanders/make-help .

# Run `build` and `help` successively
test: build help

##
## Section for authorized contributors
##

# Push image to `https://hub.docker.com`
push:
	docker push xanders/make-help

```

**Comment by Xanders** [comment]
Hi! Thank you for your interest to this tool! :) The behavior you described is definitely a bug. I'll try to fix it as soon as possible!

**Comment by Drachenfels** [comment]
Hi @Xanders,

Indeed it's something similar we used internally and one of my colleagues has found your solution and I gave it a go. :-)

Also one thing you could consider is to add some description about syntax that is supported to README. Actually I can create a pull request with it for you if you want. To be frank if I knew crystal and was crazy enough to dive deep into regexp world I would propose fix as well for bug above. 

Either way really cool small tool and I might have more bugs for you to fix in due process ;-)

**Comment by Xanders** [comment]
Hi @Drachenfels! Sorry for delay! I finally fixed the problem I hope. Please update your image:

    docker pull xanders/make-help

And try again with your file. My regexp now ignores variable definitions and comments with double newlines after them. So now it works as expected in README.

Only syntax supported right now is target and section definitions as mentioned in README, but for sure all PRs are welcome, so if you know how to make README better, please do it! :) I'm not English native speaker so there are may be a lot of bugs in the README too, not only in code, lol. 🤣

**Comment by Xanders** [comment]
Please feel free to reopen issue if there are still any problems on last version!
