### ISSUE TITLE
Error from daemon: Unauthorized

### ISSUE THREAD

**Issue by muuvmuuv** [Xanders/make-help#5]
Trying to pull latest image returns:

Error response from daemon: Head https://registry-1.docker.io/v2/xanders/make-help/manifests/latest: unauthorized: incorrect username or password

**Comment by Xanders** [comment]
Hi! I believe it is something related to your username or password since my Docker Hub account works, repo is here and pulling works on my computer. Did you try to pull any other image from Docker Hub?

**Comment by muuvmuuv** [comment]
I wasn't aware I need to be logged in into Hub, since other pulls work as well. Will try that.

**Comment by muuvmuuv** [comment]
That is weird. I was logged in on the Docker Desktop app, after logging in into CLI with docker login it works. Still weird since other images worked without logging in.

**Comment by Xanders** [comment]
It's quite strange for sure. I believe anyone should be able to pull public images without authentication. Maybe some temporarily bug on Docker Hub side.
